import os

keys_es = {
    'AprobacionesRepartidores': 'Aprobaciones de Repartidores',
    'SolicitudesRepartidoresPendientes': 'Solicitudes de Repartidores Pendientes',
    'NoHaySolicitudesPendientes': 'No hay solicitudes pendientes en este momento.',
    'PerfilTag': 'Perfil',
    'NombreTag': 'Nombre',
    'EmailTag': 'Email',
    'CedulaTag': 'Cédula',
    'FechaRegistroTag': 'Fecha Registro',
    'AccionesTag': 'Acciones',
    'MostrarInformacionBtn': 'Mostrar información',
    'AprobarBtn': 'Aprobar',
    'DenegarBtn': 'Denegar',
    'InfoRepartidorTitle': 'Información del Repartidor',
    'DatosPersonalesTitle': 'Datos Personales',
    'TelefonoTag': 'Teléfono',
    'DatosVehiculoTitle': 'Datos del Vehículo',
    'TipoVehiculoTag': 'Tipo',
    'PlacaTag': 'Placa',
    'LicenciaTag': 'Licencia',
    'FotoLicenciaTag': 'Foto de Licencia',
    'CerrarBtn': 'Cerrar',
    'DenegarSolicitudTitle': 'Denegar Solicitud',
    'SeguroDenegarSolicitud': '¿Estás seguro que deseas denegar la solicitud de',
    'MotivoRechazoObligatorio': 'Motivo del rechazo (obligatorio)',
    'CancelarBtn': 'Cancelar',
    'ConfirmarDenegacionBtn': 'Confirmar Denegación',
    'AprobacionesRestaurantes': 'Aprobaciones de Restaurantes',
    'SolicitudesRestaurantesPendientes': 'Solicitudes de Restaurantes Pendientes',
    'LogoTag': 'Logo',
    'RestauranteTag': 'Restaurante',
    'CategoriaTag': 'Categoría',
    'PropietarioTag': 'Propietario',
    'InfoRestauranteTitle': 'Información del Restaurante',
    'DatosEstablecimientoTitle': 'Datos del Establecimiento',
    'RUCTag': 'RUC',
    'DireccionTag': 'Dirección',
    'DescripcionTag': 'Descripción',
    'DatosPropietarioTitle': 'Datos del Propietario',
    'EmailPropietarioTag': 'Email Propietario',
    'SeguroDenegarSolicitudRest': '¿Estás seguro que deseas denegar la solicitud del restaurante',
    'GestionCupones': 'Gestión de Cupones',
    'CuponesSistema': 'Cupones del Sistema',
    'CodigoTag': 'Código',
    'DescuentoTag': 'Descuento',
    'ActivoTag': 'Activo',
    'SiTag': 'Sí',
    'NoTag': 'No',
    'GestionPedidos': 'Gestión de Pedidos',
    'TodosLosPedidos': 'Todos los Pedidos',
    'ClienteIDTag': 'Cliente ID',
    'RestauranteIDTag': 'Restaurante ID',
    'EstadoTag': 'Estado',
    'TotalTag': 'Total',
    'GestionProductos': 'Gestión de Productos',
    'TodosLosProductos': 'Todos los Productos',
    'PrecioTag': 'Precio',
    'GestionRepartidores': 'Gestión de Repartidores',
    'RepartidoresRegistrados': 'Repartidores Registrados',
    'VistaBasicaAdminParaAprobarRep': 'Vista básica para el administrador. Para aprobar o rechazar, ir a Solicitudes.',
    'GestionRestaurantes': 'Gestión de Restaurantes',
    'RestaurantesRegistrados': 'Restaurantes Registrados',
    'VistaBasicaAdminParaAprobarRest': 'Vista básica para el administrador. Para aprobar o rechazar, ir a Solicitudes.',
    'NombreComercialTag': 'Nombre Comercial',
    'GestionUsuarios': 'Gestión de Usuarios',
    'UsuariosSistema': 'Usuarios del Sistema',
    'VistaBasicaLecturaUsuarios': 'Esta es una vista básica de solo lectura para evitar errores 404.',
    'PanelAdministrador': 'Panel de Administrador',
    'PanelAdministracion': 'Panel de Administración',
    'BienvenidoCentroControl': 'Bienvenido al centro de control de RayoExpres. Desde aquí puedes gestionar todos los módulos del sistema.',
    'UsuariosCardTitle': 'Usuarios',
    'GestionaUsuariosDesc': 'Gestiona los usuarios, clientes, y administradores.',
    'IrAUsuariosBtn': 'Ir a Usuarios',
    'RestaurantesCardTitle': 'Restaurantes',
    'AdministraRestaurantesDesc': 'Administra los restaurantes afiliados al sistema.',
    'IrARestaurantesBtn': 'Ir a Restaurantes',
    'ProductosCardTitle': 'Productos',
    'ControlGeneralCatalogoDesc': 'Control general del catálogo de productos.',
    'IrAProductosBtn': 'Ir a Productos',
    'CategoriasCardTitle': 'Categorías',
    'GestionCategoriasDesc': 'Gestión de categorías de productos.',
    'IrACategoriasBtn': 'Ir a Categorías',
    'PedidosCardTitle': 'Pedidos',
    'VisualizaPedidosDesc': 'Visualiza todos los pedidos generados.',
    'IrAPedidosBtn': 'Ir a Pedidos',
    'RepartidoresCardTitle': 'Repartidores',
    'GestionRepartidoresEstadosDesc': 'Gestión de repartidores y sus estados.',
    'IrARepartidoresBtn': 'Ir a Repartidores',
    'VehiculosCardTitle': 'Vehículos',
    'GestionVehiculosDesc': 'Gestión de vehículos de los repartidores.',
    'IrAVehiculosBtn': 'Ir a Vehículos',
    'CuponesCardTitle': 'Cupones',
    'AdministracionPromocionesDesc': 'Administración de promociones y cupones.',
    'IrACuponesBtn': 'Ir a Cupones',
    'PagosCardTitle': 'Pagos',
    'HistorialTransaccionesDesc': 'Historial de transacciones y pagos.',
    'IrAPagosBtn': 'Ir a Pagos',
    'CalificacionesCardTitle': 'Calificaciones',
    'ModeracionResenasDesc': 'Moderación de reseñas a restaurantes y repartidores.',
    'IrAResenasBtn': 'Ir a Reseñas',
    'AuditoriaCardTitle': 'Auditoría',
    'RegistrosAccionesDesc': 'Registros de acciones importantes en el sistema.',
    'IrAAuditoriaBtn': 'Ir a Auditoría',
    'RepartidorAprobadoMsj': 'Repartidor aprobado.',
    'RepartidorRechazadoMsj': 'Repartidor rechazado.',
    'RestauranteAprobadoMsj': 'Restaurante aprobado.',
    'RestauranteRechazadoMsj': 'Restaurante rechazado.'
}

keys_en = {
    'AprobacionesRepartidores': 'Driver Approvals',
    'SolicitudesRepartidoresPendientes': 'Pending Driver Requests',
    'NoHaySolicitudesPendientes': 'There are no pending requests at this time.',
    'PerfilTag': 'Profile',
    'NombreTag': 'Name',
    'EmailTag': 'Email',
    'CedulaTag': 'ID Number',
    'FechaRegistroTag': 'Registration Date',
    'AccionesTag': 'Actions',
    'MostrarInformacionBtn': 'Show information',
    'AprobarBtn': 'Approve',
    'DenegarBtn': 'Deny',
    'InfoRepartidorTitle': 'Driver Information',
    'DatosPersonalesTitle': 'Personal Data',
    'TelefonoTag': 'Phone',
    'DatosVehiculoTitle': 'Vehicle Data',
    'TipoVehiculoTag': 'Type',
    'PlacaTag': 'Plate',
    'LicenciaTag': 'License',
    'FotoLicenciaTag': 'License Photo',
    'CerrarBtn': 'Close',
    'DenegarSolicitudTitle': 'Deny Request',
    'SeguroDenegarSolicitud': 'Are you sure you want to deny the request of',
    'MotivoRechazoObligatorio': 'Reason for denial (required)',
    'CancelarBtn': 'Cancel',
    'ConfirmarDenegacionBtn': 'Confirm Denial',
    'AprobacionesRestaurantes': 'Restaurant Approvals',
    'SolicitudesRestaurantesPendientes': 'Pending Restaurant Requests',
    'LogoTag': 'Logo',
    'RestauranteTag': 'Restaurant',
    'CategoriaTag': 'Category',
    'PropietarioTag': 'Owner',
    'InfoRestauranteTitle': 'Restaurant Information',
    'DatosEstablecimientoTitle': 'Establishment Data',
    'RUCTag': 'Tax ID',
    'DireccionTag': 'Address',
    'DescripcionTag': 'Description',
    'DatosPropietarioTitle': 'Owner Data',
    'EmailPropietarioTag': 'Owner Email',
    'SeguroDenegarSolicitudRest': 'Are you sure you want to deny the request for the restaurant',
    'GestionCupones': 'Coupon Management',
    'CuponesSistema': 'System Coupons',
    'CodigoTag': 'Code',
    'DescuentoTag': 'Discount',
    'ActivoTag': 'Active',
    'SiTag': 'Yes',
    'NoTag': 'No',
    'GestionPedidos': 'Order Management',
    'TodosLosPedidos': 'All Orders',
    'ClienteIDTag': 'Client ID',
    'RestauranteIDTag': 'Restaurant ID',
    'EstadoTag': 'Status',
    'TotalTag': 'Total',
    'GestionProductos': 'Product Management',
    'TodosLosProductos': 'All Products',
    'PrecioTag': 'Price',
    'GestionRepartidores': 'Driver Management',
    'RepartidoresRegistrados': 'Registered Drivers',
    'VistaBasicaAdminParaAprobarRep': 'Basic view for the administrator. To approve or reject, go to Requests.',
    'GestionRestaurantes': 'Restaurant Management',
    'RestaurantesRegistrados': 'Registered Restaurants',
    'VistaBasicaAdminParaAprobarRest': 'Basic view for the administrator. To approve or reject, go to Requests.',
    'NombreComercialTag': 'Trade Name',
    'GestionUsuarios': 'User Management',
    'UsuariosSistema': 'System Users',
    'VistaBasicaLecturaUsuarios': 'This is a basic read-only view to avoid 404 errors.',
    'PanelAdministrador': 'Admin Panel',
    'PanelAdministracion': 'Administration Panel',
    'BienvenidoCentroControl': 'Welcome to the RayoExpres control center. From here you can manage all system modules.',
    'UsuariosCardTitle': 'Users',
    'GestionaUsuariosDesc': 'Manage users, clients, and administrators.',
    'IrAUsuariosBtn': 'Go to Users',
    'RestaurantesCardTitle': 'Restaurants',
    'AdministraRestaurantesDesc': 'Manage affiliated restaurants.',
    'IrARestaurantesBtn': 'Go to Restaurants',
    'ProductosCardTitle': 'Products',
    'ControlGeneralCatalogoDesc': 'General control of the product catalog.',
    'IrAProductosBtn': 'Go to Products',
    'CategoriasCardTitle': 'Categories',
    'GestionCategoriasDesc': 'Product category management.',
    'IrACategoriasBtn': 'Go to Categories',
    'PedidosCardTitle': 'Orders',
    'VisualizaPedidosDesc': 'View all generated orders.',
    'IrAPedidosBtn': 'Go to Orders',
    'RepartidoresCardTitle': 'Drivers',
    'GestionRepartidoresEstadosDesc': 'Driver management and statuses.',
    'IrARepartidoresBtn': 'Go to Drivers',
    'VehiculosCardTitle': 'Vehicles',
    'GestionVehiculosDesc': 'Driver vehicle management.',
    'IrAVehiculosBtn': 'Go to Vehicles',
    'CuponesCardTitle': 'Coupons',
    'AdministracionPromocionesDesc': 'Administration of promotions and coupons.',
    'IrACuponesBtn': 'Go to Coupons',
    'PagosCardTitle': 'Payments',
    'HistorialTransaccionesDesc': 'Transaction and payment history.',
    'IrAPagosBtn': 'Go to Payments',
    'CalificacionesCardTitle': 'Ratings',
    'ModeracionResenasDesc': 'Moderation of restaurant and driver reviews.',
    'IrAResenasBtn': 'Go to Reviews',
    'AuditoriaCardTitle': 'Audit',
    'RegistrosAccionesDesc': 'Logs of important system actions.',
    'IrAAuditoriaBtn': 'Go to Audit',
    'RepartidorAprobadoMsj': 'Driver approved.',
    'RepartidorRechazadoMsj': 'Driver denied.',
    'RestauranteAprobadoMsj': 'Restaurant approved.',
    'RestauranteRechazadoMsj': 'Restaurant denied.'
}

def append_to_resx(filepath, keys):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    xml_data = ""
    for k, v in keys.items():
        safe_k = k.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;").replace("'", "&apos;")
        safe_v = v.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;").replace("'", "&apos;")
        xml_data += f'  <data name="{safe_k}" xml:space="preserve"><value>{safe_v}</value></data>\n'
    
    content = content.replace('</root>', xml_data + '</root>')
    
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)

append_to_resx('Delivery.MVC/Resources/SharedResource.es.resx', keys_es)
append_to_resx('Delivery.MVC/Resources/SharedResource.en.resx', keys_en)
