import os

keys_es = {
    # Checkout
    'CheckoutTitulo': 'Checkout',
    'ProcesoPago': 'Proceso de Pago',
    'TuCarrito': 'Tu Carrito',
    'Cantidad': 'Cantidad:',
    'Subtotal': 'Subtotal',
    'DistanciaTiempo': 'Distancia y Tiempo',
    'Pendiente': 'Pendiente',
    'SeleccioneDireccionMapa': 'Seleccione dirección en el mapa',
    'CostoEnvio': 'Costo de Envío',
    'CuponAplicado': 'Cupón aplicado',
    'TotalUSD': 'Total (USD)',
    'SeleccionarCupon': '-- Seleccionar cupón --',
    'AplicarCuponBtn': 'Aplicar cupón',
    'TarifaEnvioTag': 'Tarifa de envío:',
    'TarifaEnvioDesc': '$1.50 (hasta 3 km). $0.25 por km adicional.',
    'DireccionEntrega': 'Dirección de Entrega',
    'TusDirecciones': 'Tus direcciones guardadas',
    'UsarOtraDireccion': '-- Usar otra dirección (Buscar en el mapa) --',
    'BuscarCallePlaceHolder': '🔍 Escribe para buscar una calle o lugar...',
    'ArrastrarMarcadorDesc': '📍 Puedes arrastrar el marcador rojo para afinar tu ubicación exacta.',
    'DetallesUbicacion': 'Detalles de la Ubicación',
    'CalleAvenidaDetectada': 'Calle / Avenida principal detectada',
    'GuardarDireccionParaCompras': 'Guardar esta dirección para mis próximas compras',
    'AliasEjemplo': 'Alias (Ej. Casa, Trabajo)',
    'CasaPlaceholder': 'Casa',
    'Referencia': 'Referencia',
    'FrenteParquePlaceholder': 'Frente al parque',
    'MetodoPago': 'Método de Pago',
    'EfectivoDesc': 'Efectivo (Al recibir el pedido)',
    'TarjetaDesc': 'Tarjeta de Crédito / Débito',
    'TransferenciaDesc': 'Transferencia Bancaria',
    'DetallesTarjeta': 'Detalles de la Tarjeta',
    'NombreTarjeta': 'Nombre en la tarjeta',
    'EjemploJuanPerez': 'EJ. JUAN PEREZ',
    'NumeroTarjeta': 'Número de tarjeta',
    'Expiracion': 'Expiración',
    'CVV': 'CVV',
    'DatosTransferencia': 'Datos para Transferencia',
    'TransferenciaInstrucciones': 'Por favor, realiza la transferencia a la siguiente cuenta y adjunta el comprobante (JPG, PNG, PDF).',
    'BancoTag': 'Banco:',
    'BeneficiarioTag': 'Beneficiario:',
    'RUCTag': 'RUC:',
    'TipoCuentaTag': 'Tipo de Cuenta:',
    'CorrienteDesc': 'Corriente',
    'NumCuentaTag': 'Número de cuenta:',
    'SubirComprobante': 'Subir Comprobante',
    'ConfirmarPagarBtn': 'Confirmar y Pagar',
    # Carrito Index
    'MiCarrito': 'Mi Carrito',
    'CarritoVacio': 'Tu carrito está vacío',
    'CarritoVacioDesc': 'Explora los restaurantes y agrega productos para comenzar tu pedido.',
    'VerRestaurantesBtn': 'Ver Restaurantes',
    'RestauranteTag': 'Restaurante',
    'ProductoCol': 'Producto',
    'PrecioUnitarioCol': 'Precio Unitario',
    'CantidadCol': 'Cantidad',
    'SubtotalCol': 'Subtotal',
    'AccionCol': 'Acción',
    'QuitarBtn': 'Quitar',
    'TotalCol': 'Total',
    'VaciarCarritoBtn': 'Vaciar Carrito',
    'SinDireccionAlert': 'No tienes ninguna dirección de entrega registrada.',
    'SinDireccionDesc': 'Debes agregar una dirección antes de confirmar tu pedido.',
    'AgregarDireccionBtn': 'Agregar Mi Primera Dirección',
    'ProcederPagoBtn': 'Proceder al Pago',
    # Cupones
    'MisCupones': 'Mis Cupones',
    'GestionaCupones': 'Gestiona tus cupones de descuento y códigos promocionales.',
    'AgregarCuponBtn': 'Agregar Cupón',
    'RegistrarNuevoCupon': 'Registrar Nuevo Cupón',
    'CodigoCuponTag': 'Código del cupón',
    'IngresarCodigoPlaceholder': 'Ingresar código',
    'CancelarBtn': 'Cancelar',
    'AgregarBtn': 'Agregar',
    'SinCupones': 'Aún no tienes cupones registrados.',
    'SinCuponesDesc': 'Ingresa un código en la parte superior para agregarlo a tu cuenta.',
    'Disponible': 'DISPONIBLE',
    'Utilizado': 'UTILIZADO',
    'Vencido': 'VENCIDO',
    'DescripcionTag': 'Descripción:',
    'TopeMaximoTag': 'Tope máximo:',
    'VenceTag': 'Vence:',
    'DiasRestantesTag': 'Días restantes:',
    'ExpiraHoy': 'Expira hoy',
    'RegistradoTag': 'Registrado:',
    'CompraMinimaTag': 'Compra mínima:',
    'CopiarCodigoBtn': 'Copiar Código',
    'UtilizadoElTag': 'Utilizado el ',
    # Direcciones
    'NuevaDireccion': 'Nueva Dirección',
    'BuscaMapaDireccionDesc': 'Busca en el mapa o haz clic para ubicar tu dirección exacta.',
    'BuscarLugarTag': 'Buscar Lugar',
    'EjemploBuscarLugar': 'Ej: Ibarra, Parque Ciudad Blanca...',
    'BuscarBtn': 'Buscar',
    'BuscaBarrioMapaDesc': 'Busca tu barrio o calle y haz clic en el mapa.',
    'AliasTag': 'Alias (Casa, Trabajo...)',
    'EjemploCasa': 'Ej: Casa',
    'CallePrincipalTag': 'Calle Principal',
    'EjemploCalle': 'Ej: Av. 17 de Julio',
    'NumeroTag': 'Número',
    'EjemploNumero': 'Ej: 5-32',
    'InterseccionTag': 'Intersección',
    'EjemploInterseccion': 'Ej: Calle 2',
    'ReferenciaTag': 'Referencia',
    'EjemploReferencia': 'Ej: Frente al parque',
    'CiudadTag': 'Ciudad',
    'EjemploCiudad': 'Ej: Ibarra',
    'UbicacionGPSTag': 'Ubicación GPS',
    'MapaRellenaraDesc': 'El mapa rellenará estos campos automáticamente.',
    'LatitudTag': 'Latitud',
    'LongitudTag': 'Longitud',
    'GuardarDireccionBtn': 'Guardar Dirección',
    'VolverListaBtn': 'Volver a la lista',
    'MisDirecciones': 'Mis Direcciones',
    'GestionaDireccionesDesc': 'Gestiona tus direcciones de entrega para agilizar tus pedidos.',
    'NuevaDireccionBtn': 'Nueva Dirección',
    'SinDirecciones': 'Aún no tienes direcciones registradas.',
    'AgregaPrimeraDireccionDesc': 'Agrega tu primera dirección para comenzar a pedir.',
    'EditarBtn': 'Editar',
    'EliminarBtn': 'Eliminar',
    'EditarDireccion': 'Editar Dirección',
    'ActualizaLugarEntregaDesc': 'Actualiza la información de tu lugar de entrega.',
    'BuscaBarrioMapaActDesc': 'Busca tu barrio o calle y haz clic en el mapa para actualizar coordenadas.',
    'MapaActualizaraDesc': 'El mapa actualizará estos campos.',
    'GuardarCambiosBtn': 'Guardar Cambios',
    'EliminarDireccion': 'Eliminar Dirección',
    'ConfirmarEliminarDireccion': '¿Estás seguro de que deseas eliminar esta dirección?',
    'AccionNoDeshacer': 'Esta acción no se puede deshacer.',
    'SiEliminarDireccionBtn': 'Sí, Eliminar Dirección',
    'DetallesDireccion': 'Detalles de Dirección',
    # Favoritos
    'MisFavoritos': 'Mis Favoritos',
    'CrearNuevoBtn': 'Crear Nuevo',
    'UsuarioIdTag': 'UsuarioId',
    'RestauranteIdTag': 'RestauranteId',
    'FechaAgregadoTag': 'Fecha Agregado',
    'UsuarioTag': 'Usuario',
    'AccionesTag': 'Acciones',
    'DetallesBtn': 'Detalles',
    'EliminarFavorito': 'Eliminar Favorito',
    'SeguroEliminarFavorito': '¿Estás seguro de que quieres eliminar esto?',
    # Historial Pedidos
    'CalificarPedido': 'Calificar Pedido',
    'CalificacionEstrellasTag': 'Calificación (1 a 5 estrellas)',
    'CincoExcelente': '5 - Excelente',
    'CuatroMuyBueno': '4 - Muy Bueno',
    'TresBueno': '3 - Bueno',
    'DosRegular': '2 - Regular',
    'UnoMalo': '1 - Malo',
    'ComentarioOpcionalTag': 'Comentario (Opcional)',
    'QueTeParecioComidaPlaceholder': '¿Qué te pareció la comida y el servicio?',
    'EnviarCalificacionBtn': 'Enviar Calificación',
    'DetallePedido': 'Detalle del Pedido',
    'DetallesTuPedido': 'Detalles de tu Pedido',
    'InformacionGeneralTag': 'Información General',
    'FechaPedidoTag': 'Fecha Pedido',
    'EstadoTag': 'Estado',
    'DireccionTag': 'Dirección',
    'MetodoPagoTag': 'Método de Pago',
    'RepartidorTag': 'Repartidor',
    'LicenciaTag': 'Licencia',
    'NotasTag': 'Notas',
    'ResumenPedidoTag': 'Resumen del Pedido',
    'CantCol': 'Cant.',
    'PrecioCol': 'Precio',
    'ProductoIDTag': 'Producto ID',
    'TotalPagadoTag': 'Total Pagado',
    'VolverHistorialBtn': 'Volver al Historial',
    'MisPedidos': 'Mis Pedidos',
    'RevisaHistorialDesc': 'Revisa el historial de tus compras y su estado.',
    'FiltroEstadoTag': 'Filtro Estado',
    'TodosTag': 'Todos',
    'FiltrarBtn': 'Filtrar',
    'NoSeEncontraronPedidos': 'No se encontraron pedidos.',
    'NoTienesPedidosRegistrados': 'No tienes pedidos registrados todavía.',
    'ExplorarRestaurantesBtn': 'Explorar Restaurantes',
    'PedidoTag': 'Pedido',
    'ArticulosTag': 'Artículos',
    'TotalTag': 'Total',
    'VerDetallesBtn': 'Ver Detalles',
    'CalificarBtn': '¡Calificar!',
    # Perfil
    'CompletarPerfil': 'Completar Perfil',
    'CompletarMiPerfil': 'Completar Mi Perfil',
    'SubirFotoPerfilTag': 'Subir Foto de Perfil (Opcional)',
    'NombresTag': 'Nombres',
    'ApellidosTag': 'Apellidos',
    'TelefonoTag': 'Teléfono',
    'CedulaTag': 'Cédula',
    'GuardarPerfilBtn': 'Guardar Perfil',
    'SeleccionarArchivoBtn': 'Seleccionar archivo',
    # Controllers
    'ErrorAgregarProducto': 'No se pudo agregar el producto. Puede que debas vaciar el carrito si es de otro restaurante.',
    'ExitoAgregarProducto': 'Producto agregado al carrito.',
    'CarritoVacioError': 'Tu carrito está vacío.',
    'RegistrarDireccionError': 'Necesitas registrar una dirección antes de confirmar tu pedido.',
    'UbicacionValidaError': 'Debes proporcionar una ubicación válida en el mapa.',
    'ErrorGuardarUbicacion': 'No se pudo guardar la ubicación en el sistema.',
    'DireccionInvalidaError': 'Debes seleccionar una dirección de entrega válida.',
    'CamposTarjetaError': 'Todos los campos de la tarjeta son obligatorios.',
    'TarjetaInvalidaError': 'El número de tarjeta no es válido (Validación Luhn fallida).',
    'TarjetaNoSoportadaError': 'La tarjeta no es Visa, Mastercard, Amex ni Discover.',
    'ErrorProcesarPedido': 'Hubo un problema al procesar tu pedido. Por favor intenta de nuevo.',
    'IngresarCodigoError': 'Debes ingresar un código.',
    'CuponDesactivadoError': 'El cupón se encuentra desactivado.',
    'CuponExpiradoError': 'El cupón ha expirado.',
    'CuponUtilizadoError': 'Este cupón ya fue utilizado.',
    'CuponAgregadoError': 'Este cupón ya fue agregado.',
    'DireccionEliminadaExito': 'Dirección eliminada correctamente.',
    'DireccionAsociadaPedidoError': 'No se puede eliminar la dirección porque está asociada a uno o más pedidos en el historial.',
    'PerfilActualizadoExito': 'Perfil actualizado exitosamente.'
}

keys_en = {
    # Checkout
    'CheckoutTitulo': 'Checkout',
    'ProcesoPago': 'Payment Process',
    'TuCarrito': 'Your Cart',
    'Cantidad': 'Quantity:',
    'Subtotal': 'Subtotal',
    'DistanciaTiempo': 'Distance & Time',
    'Pendiente': 'Pending',
    'SeleccioneDireccionMapa': 'Select an address on the map',
    'CostoEnvio': 'Shipping Cost',
    'CuponAplicado': 'Coupon Applied',
    'TotalUSD': 'Total (USD)',
    'SeleccionarCupon': '-- Select coupon --',
    'AplicarCuponBtn': 'Apply coupon',
    'TarifaEnvioTag': 'Shipping rate:',
    'TarifaEnvioDesc': '$1.50 (up to 3 km). $0.25 per additional km.',
    'DireccionEntrega': 'Delivery Address',
    'TusDirecciones': 'Your saved addresses',
    'UsarOtraDireccion': '-- Use another address (Search on map) --',
    'BuscarCallePlaceHolder': '🔍 Type to search for a street or place...',
    'ArrastrarMarcadorDesc': '📍 You can drag the red marker to refine your exact location.',
    'DetallesUbicacion': 'Location Details',
    'CalleAvenidaDetectada': 'Main Street / Avenue detected',
    'GuardarDireccionParaCompras': 'Save this address for my next purchases',
    'AliasEjemplo': 'Alias (e.g. Home, Work)',
    'CasaPlaceholder': 'Home',
    'Referencia': 'Reference',
    'FrenteParquePlaceholder': 'In front of the park',
    'MetodoPago': 'Payment Method',
    'EfectivoDesc': 'Cash (On delivery)',
    'TarjetaDesc': 'Credit / Debit Card',
    'TransferenciaDesc': 'Bank Transfer',
    'DetallesTarjeta': 'Card Details',
    'NombreTarjeta': 'Name on card',
    'EjemploJuanPerez': 'E.G. JOHN DOE',
    'NumeroTarjeta': 'Card Number',
    'Expiracion': 'Expiration',
    'CVV': 'CVV',
    'DatosTransferencia': 'Transfer Details',
    'TransferenciaInstrucciones': 'Please transfer to the following account and attach the receipt (JPG, PNG, PDF).',
    'BancoTag': 'Bank:',
    'BeneficiarioTag': 'Beneficiary:',
    'RUCTag': 'Tax ID:',
    'TipoCuentaTag': 'Account Type:',
    'CorrienteDesc': 'Checking',
    'NumCuentaTag': 'Account Number:',
    'SubirComprobante': 'Upload Receipt',
    'ConfirmarPagarBtn': 'Confirm and Pay',
    # Carrito Index
    'MiCarrito': 'My Cart',
    'CarritoVacio': 'Your cart is empty',
    'CarritoVacioDesc': 'Explore restaurants and add products to start your order.',
    'VerRestaurantesBtn': 'View Restaurants',
    'RestauranteTag': 'Restaurant',
    'ProductoCol': 'Product',
    'PrecioUnitarioCol': 'Unit Price',
    'CantidadCol': 'Quantity',
    'SubtotalCol': 'Subtotal',
    'AccionCol': 'Action',
    'QuitarBtn': 'Remove',
    'TotalCol': 'Total',
    'VaciarCarritoBtn': 'Empty Cart',
    'SinDireccionAlert': 'You have no registered delivery address.',
    'SinDireccionDesc': 'You must add an address before confirming your order.',
    'AgregarDireccionBtn': 'Add My First Address',
    'ProcederPagoBtn': 'Proceed to Checkout',
    # Cupones
    'MisCupones': 'My Coupons',
    'GestionaCupones': 'Manage your discount coupons and promo codes.',
    'AgregarCuponBtn': 'Add Coupon',
    'RegistrarNuevoCupon': 'Register New Coupon',
    'CodigoCuponTag': 'Coupon code',
    'IngresarCodigoPlaceholder': 'Enter code',
    'CancelarBtn': 'Cancel',
    'AgregarBtn': 'Add',
    'SinCupones': 'You have no registered coupons yet.',
    'SinCuponesDesc': 'Enter a code above to add it to your account.',
    'Disponible': 'AVAILABLE',
    'Utilizado': 'USED',
    'Vencido': 'EXPIRED',
    'DescripcionTag': 'Description:',
    'TopeMaximoTag': 'Maximum cap:',
    'VenceTag': 'Expires:',
    'DiasRestantesTag': 'Days remaining:',
    'ExpiraHoy': 'Expires today',
    'RegistradoTag': 'Registered:',
    'CompraMinimaTag': 'Minimum purchase:',
    'CopiarCodigoBtn': 'Copy Code',
    'UtilizadoElTag': 'Used on ',
    # Direcciones
    'NuevaDireccion': 'New Address',
    'BuscaMapaDireccionDesc': 'Search on the map or click to locate your exact address.',
    'BuscarLugarTag': 'Search Place',
    'EjemploBuscarLugar': 'e.g. Central Park...',
    'BuscarBtn': 'Search',
    'BuscaBarrioMapaDesc': 'Search for your neighborhood or street and click on the map.',
    'AliasTag': 'Alias (Home, Work...)',
    'EjemploCasa': 'e.g. Home',
    'CallePrincipalTag': 'Main Street',
    'EjemploCalle': 'e.g. 5th Avenue',
    'NumeroTag': 'Number',
    'EjemploNumero': 'e.g. 5-32',
    'InterseccionTag': 'Intersection',
    'EjemploInterseccion': 'e.g. 2nd Street',
    'ReferenciaTag': 'Reference',
    'EjemploReferencia': 'e.g. In front of the park',
    'CiudadTag': 'City',
    'EjemploCiudad': 'e.g. New York',
    'UbicacionGPSTag': 'GPS Location',
    'MapaRellenaraDesc': 'The map will auto-fill these fields.',
    'LatitudTag': 'Latitude',
    'LongitudTag': 'Longitude',
    'GuardarDireccionBtn': 'Save Address',
    'VolverListaBtn': 'Back to list',
    'MisDirecciones': 'My Addresses',
    'GestionaDireccionesDesc': 'Manage your delivery addresses to speed up your orders.',
    'NuevaDireccionBtn': 'New Address',
    'SinDirecciones': 'You have no registered addresses yet.',
    'AgregaPrimeraDireccionDesc': 'Add your first address to start ordering.',
    'EditarBtn': 'Edit',
    'EliminarBtn': 'Delete',
    'EditarDireccion': 'Edit Address',
    'ActualizaLugarEntregaDesc': 'Update your delivery location information.',
    'BuscaBarrioMapaActDesc': 'Search your neighborhood or street and click on the map to update coordinates.',
    'MapaActualizaraDesc': 'The map will update these fields.',
    'GuardarCambiosBtn': 'Save Changes',
    'EliminarDireccion': 'Delete Address',
    'ConfirmarEliminarDireccion': 'Are you sure you want to delete this address?',
    'AccionNoDeshacer': 'This action cannot be undone.',
    'SiEliminarDireccionBtn': 'Yes, Delete Address',
    'DetallesDireccion': 'Address Details',
    # Favoritos
    'MisFavoritos': 'My Favorites',
    'CrearNuevoBtn': 'Create New',
    'UsuarioIdTag': 'UserId',
    'RestauranteIdTag': 'RestaurantId',
    'FechaAgregadoTag': 'Date Added',
    'UsuarioTag': 'User',
    'AccionesTag': 'Actions',
    'DetallesBtn': 'Details',
    'EliminarFavorito': 'Delete Favorite',
    'SeguroEliminarFavorito': 'Are you sure you want to delete this?',
    # Historial Pedidos
    'CalificarPedido': 'Rate Order',
    'CalificacionEstrellasTag': 'Rating (1 to 5 stars)',
    'CincoExcelente': '5 - Excellent',
    'CuatroMuyBueno': '4 - Very Good',
    'TresBueno': '3 - Good',
    'DosRegular': '2 - Fair',
    'UnoMalo': '1 - Poor',
    'ComentarioOpcionalTag': 'Comment (Optional)',
    'QueTeParecioComidaPlaceholder': 'How was the food and service?',
    'EnviarCalificacionBtn': 'Submit Rating',
    'DetallePedido': 'Order Detail',
    'DetallesTuPedido': 'Details of your Order',
    'InformacionGeneralTag': 'General Information',
    'FechaPedidoTag': 'Order Date',
    'EstadoTag': 'Status',
    'DireccionTag': 'Address',
    'MetodoPagoTag': 'Payment Method',
    'RepartidorTag': 'Driver',
    'LicenciaTag': 'License',
    'NotasTag': 'Notes',
    'ResumenPedidoTag': 'Order Summary',
    'CantCol': 'Qty.',
    'PrecioCol': 'Price',
    'ProductoIDTag': 'Product ID',
    'TotalPagadoTag': 'Total Paid',
    'VolverHistorialBtn': 'Back to History',
    'MisPedidos': 'My Orders',
    'RevisaHistorialDesc': 'Check your purchase history and status.',
    'FiltroEstadoTag': 'Status Filter',
    'TodosTag': 'All',
    'FiltrarBtn': 'Filter',
    'NoSeEncontraronPedidos': 'No orders found.',
    'NoTienesPedidosRegistrados': 'You have no registered orders yet.',
    'ExplorarRestaurantesBtn': 'Explore Restaurants',
    'PedidoTag': 'Order',
    'ArticulosTag': 'Items',
    'TotalTag': 'Total',
    'VerDetallesBtn': 'View Details',
    'CalificarBtn': 'Rate!',
    # Perfil
    'CompletarPerfil': 'Complete Profile',
    'CompletarMiPerfil': 'Complete My Profile',
    'SubirFotoPerfilTag': 'Upload Profile Photo (Optional)',
    'NombresTag': 'First Name',
    'ApellidosTag': 'Last Name',
    'TelefonoTag': 'Phone',
    'CedulaTag': 'ID Number',
    'GuardarPerfilBtn': 'Save Profile',
    'SeleccionarArchivoBtn': 'Choose file',
    # Controllers
    'ErrorAgregarProducto': 'Could not add the product. You might need to empty your cart if it is from another restaurant.',
    'ExitoAgregarProducto': 'Product added to cart.',
    'CarritoVacioError': 'Your cart is empty.',
    'RegistrarDireccionError': 'You need to register an address before confirming your order.',
    'UbicacionValidaError': 'You must provide a valid location on the map.',
    'ErrorGuardarUbicacion': 'Could not save the location in the system.',
    'DireccionInvalidaError': 'You must select a valid delivery address.',
    'CamposTarjetaError': 'All card fields are required.',
    'TarjetaInvalidaError': 'The card number is invalid (Luhn validation failed).',
    'TarjetaNoSoportadaError': 'The card is not Visa, Mastercard, Amex or Discover.',
    'ErrorProcesarPedido': 'There was a problem processing your order. Please try again.',
    'IngresarCodigoError': 'You must enter a code.',
    'CuponDesactivadoError': 'The coupon is deactivated.',
    'CuponExpiradoError': 'The coupon has expired.',
    'CuponUtilizadoError': 'This coupon has already been used.',
    'CuponAgregadoError': 'This coupon has already been added.',
    'DireccionEliminadaExito': 'Address deleted successfully.',
    'DireccionAsociadaPedidoError': 'The address cannot be deleted because it is associated with one or more orders in history.',
    'PerfilActualizadoExito': 'Profile updated successfully.'
}

def append_to_resx(filepath, keys):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    xml_data = ""
    for k, v in keys.items():
        safe_k = k.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;").replace("'", "&apos;")
        safe_v = v.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;").replace("'", "&apos;")
        xml_data += f'  <data name="{safe_k}" xml:space="preserve"><value>{safe_v}</value></data>\n'
    
    content = content.replace('</root>', xml_data + '</root>')
    
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)

append_to_resx('Delivery.MVC/Resources/SharedResource.es.resx', keys_es)
append_to_resx('Delivery.MVC/Resources/SharedResource.en.resx', keys_en)
