// <auto-generated />
using System;
using Delivery.Modelos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Delivery.Modelos.Migrations
{
    [DbContext(typeof(DeliveryDbContext))]
    [Migration("20260710051236_AddProfileFields")]
    partial class AddProfileFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "estado_aprobacion_enum", new[] { "pendiente", "aprobado", "rechazado" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "estado_pago_enum", new[] { "pendiente", "completado", "fallido", "reembolsado" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "estado_pedido_enum", new[] { "borrador", "pendiente", "aceptado", "en_preparacion", "en_camino", "entregado", "cancelado" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "estado_restaurante_enum", new[] { "pendiente", "aprobado", "rechazado", "suspendido" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tipo_accion_auditoria_enum", new[] { "crear", "editar", "eliminar", "cambio_estado", "inicio_sesion", "cierre_sesion" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tipo_descuento_enum", new[] { "porcentaje", "monto_fijo" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tipo_metodo_pago_enum", new[] { "efectivo", "tarjeta", "transferencia", "billetera_digital" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tipo_usuario_enum", new[] { "administrador", "cliente", "repartidor", "restaurante" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tipo_vehiculo_enum", new[] { "bicicleta", "motocicleta", "automovil" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Delivery.Modelos.Entidades.CategoriaProducto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.Property<long>("RestauranteId")
                        .HasColumnType("bigint")
                        .HasColumnName("restaurante_id");

                    b.HasKey("Id");

                    b.HasIndex("RestauranteId");

                    b.ToTable("categorias_producto");
                });

            modelBuilder.Entity("Delivery.Modelos.Entidades.Cupon", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<int?>("LimiteUsos")
                        .HasColumnType("integer")
                        .HasColumnName("limite_usos");

                    b.Property<decimal?>("PedidoMinimo")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("pedido_minimo");

                    b.Property<long?>("RestauranteId")
                        .HasColumnType("bigint")
                        .HasColumnName("restaurante_id");

                    b.Property<int>("TipoDescuento")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_descuento");

                    b.Property<int>("UsosActuales")
                        .HasColumnType("integer")
                        .HasColumnName("usos_actuales");

                    b.Property<decimal>("ValorDescuento")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor_descuento");

                    b.HasKey("Id");

                    b.HasIndex("RestauranteId");

                    b.ToTable("cupones");
                });

            modelBuilder.Entity("Delivery.Modelos.Entidades.CuponUsuario", b =>
                {
                    b.Property<long>("CuponId")
                        .HasColumnType("bigint")
                        .HasColumnName("cupon_id");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.Property<long>("PedidoId")
                        .HasColumnType("bigint")
                        .HasColumnName("pedido_id");

                    b.Property<DateTime>("FechaUso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_uso");

                    b.HasKey("CuponId", "UsuarioId", "PedidoId");

                    b.HasIndex("PedidoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("cupones_usuarios");
                });

            modelBuilder.Entity("Delivery.Modelos.Entidades.DetallePedido", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<string>("NotasEspeciales")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("notas_especiales");

                    b.Property<long>("PedidoId")
                        .HasColumnType("bigint")
                        .HasColumnName("pedido_id");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<long>("ProductoId")
                        .HasColumnType("bigint")
                        .HasColumnName("producto_id");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("subtotal");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("detalle_pedido");
                });

            modelBuilder.Entity("Delivery.Modelos.Entidades.Direccion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("Alias")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("alias");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("calle");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ciudad");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("boolean")
                        .HasColumnName("es_principal");

                    b.Property<decimal?>("Latitud")
                        .HasColumnType("numeric(10,8)")
                        .HasColumnName("latitud");

                    b.Property<decimal?>("Longitud")
                        .HasColumnType("numeric(11,8)")
                        .HasColumnName("longitud");

                    b.Property<string>("Numero")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero");

                    b.Property<string>("Referencia")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("referencia");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("direcciones");
                });

            modelBuilder.Entity("Delivery.Modelos.Entidades.Favorito", b =>
                {
                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.Property<long>("RestauranteId")
                        .HasColumnType("bigint")
                        .HasColumnName("restaurante_id");

                    b.Property<DateTime>("FechaAgregado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_agregado");

                    b.HasKey("UsuarioId", "RestauranteId");

                    b.HasIndex("RestauranteId");

                    b.ToTable("favoritos");
                });

            modelBuilder.Entity("Delivery.Modelos.Entidades.HistorialAsignacionesRepartidor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<long>("PedidoId")
                        .HasColumnType("bigint")
                        .HasColumnName("pedido_id");

                    b.Property<long>("RepartidorId")
                        .HasColumnType("bigint")
                        .HasColumnName("repartidor_id");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("RepartidorId");

                    b.ToTable("historial_asignaciones_repartidor");
                });

            modelBuilder.Entity("Delivery.Modelos.Entidades.Notificacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creada_en");

                    b.Property<bool>("Leida")
                        .HasColumnType("boolean")
                        .HasColumnName("leida");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mensaje");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("titulo");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("notificaciones");
                });

            modelBuilder.Entity("Delivery.Modelos.Entidades.Pago", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<int>("EstadoPago")
                        .HasColumnType("integer")
                        .HasColumnName("estado_pago");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_pago");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("monto");

                    b.Property<long>("PedidoId")
                        .HasColumnType("bigint")
                        .HasColumnName("pedido_id");

                    b.Property<string>("ReferenciaTransaccion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("referencia_transaccion");

                    b.Property<int>("TipoMetodoPago")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_metodo_pago");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("pagos");
                });

            modelBuilder.Entity("Delivery.Modelos.Entidades.Pedido", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<decimal>("CostoEnvio")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("costo_envio");

                    b.Property<long?>("CuponId")
                        .HasColumnType("bigint")
                        .HasColumnName("cupon_id");

                    b.Property<long>("DireccionEntregaId")
                        .HasColumnType("bigint")
                        .HasColumnName("direccion_entrega_id");

                    b.Property<int>("EstadoPedido")
                        .HasColumnType("integer")
                        .HasColumnName("estado_pedido");

                    b.Property<DateTime?>("FechaEntregaEstimada")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_entrega_estimada");

                    b.Property<DateTime?>("FechaEntregaReal")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_entrega_real");

                    b.Property<DateTime>("FechaPedido")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_pedido");

                    b.Property<long?>("MetodoPagoId")
                        .HasColumnType("bigint")
                        .HasColumnName("metodo_pago_id");

                    b.Property<decimal>("MontoDescuento")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("monto_descuento");

                    b.Property<string>("Notas")
                        .HasColumnType("text")
                        .HasColumnName("notas");

                    b.Property<long?>("RepartidorId")
                        .HasColumnType("bigint")
                        .HasColumnName("repartidor_id");

                    b.Property<long>("RestauranteId")
                        .HasColumnType("bigint")
                        .HasColumnName("restaurante_id");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("subtotal");

                    b.Property<int>("TipoMetodoPago")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_metodo_pago");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("DireccionEntregaId");

                    b.HasIndex("RepartidorId");

                    b.HasIndex("RestauranteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("pedidos");
                });

            modelBuilder.Entity("Delivery.Modelos.Entidades.Producto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<long?>("CategoriaId")
                        .HasColumnType("bigint")
                        .HasColumnName("categoria_id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Disponible")
                        .HasColumnType("boolean")
                        .HasColumnName("disponible");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("text")
                        .HasColumnName("imagen_url");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio");

                    b.Property<long>("RestauranteId")
                        .HasColumnType("bigint")
                        .HasColumnName("restaurante_id");

                    b.Property<int?>("TiempoPreparacion")
                        .HasColumnType("integer")
                        .HasColumnName("tiempo_preparacion");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("RestauranteId");

                    b.ToTable("productos");
                });

            modelBuilder.Entity("Delivery.Modelos.Entidades.RegistroAuditoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Detalles")
                        .HasColumnType("text")
                        .HasColumnName("detalles");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_hora");

                    b.Property<string>("ModuloAfectado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modulo_afectado");

                    b.Property<int>("TipoAccion")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_accion");

                    b.Property<long?>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("registros_auditoria");
                });

            modelBuilder.Entity("Delivery.Modelos.Entidades.Repartidor", b =>
                {
                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<long?>("AprobadoPor")
                        .HasColumnType("bigint")
                        .HasColumnName("aprobado_por");

                    b.Property<decimal?>("CalificacionPromedio")
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("calificacion_promedio");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("DatosAdicionales")
                        .HasColumnType("text")
                        .HasColumnName("datos_adicionales");

                    b.Property<string>("Direccion")
                        .HasColumnType("text")
                        .HasColumnName("direccion");

                    b.Property<bool>("Disponible")
                        .HasColumnType("boolean")
                        .HasColumnName("disponible");

                    b.Property<int>("EstadoAprobacion")
                        .HasColumnType("integer")
                        .HasColumnName("estado_aprobacion");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_aprobacion");

                    b.Property<string>("FotoLicenciaUrl")
                        .HasColumnType("text")
                        .HasColumnName("foto_licencia_url");

                    b.Property<string>("LicenciaConducir")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("licencia_conducir");

                    b.HasKey("UsuarioId");

                    b.HasIndex("AprobadoPor");

                    b.ToTable("repartidores");
                });

            modelBuilder.Entity("Delivery.Modelos.Entidades.Resena", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<short?>("CalificacionRepartidor")
                        .HasColumnType("smallint")
                        .HasColumnName("calificacion_repartidor");

                    b.Property<short?>("CalificacionRestaurante")
                        .HasColumnType("smallint")
                        .HasColumnName("calificacion_restaurante");

                    b.Property<string>("ComentarioRepartidor")
                        .HasColumnType("text")
                        .HasColumnName("comentario_repartidor");

                    b.Property<string>("ComentarioRestaurante")
                        .HasColumnType("text")
                        .HasColumnName("comentario_restaurante");

                    b.Property<DateTime>("FechaResena")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_resena");

                    b.Property<long>("PedidoId")
                        .HasColumnType("bigint")
                        .HasColumnName("pedido_id");

                    b.Property<long?>("RepartidorId")
                        .HasColumnType("bigint")
                        .HasColumnName("repartidor_id");

                    b.Property<long?>("RestauranteId")
                        .HasColumnType("bigint")
                        .HasColumnName("restaurante_id");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("RepartidorId");

                    b.HasIndex("RestauranteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("resenas");
                });

            modelBuilder.Entity("Delivery.Modelos.Entidades.Restaurante", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Abierto")
                        .HasColumnType("boolean")
                        .HasColumnName("abierto");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<long?>("AprobadoPor")
                        .HasColumnType("bigint")
                        .HasColumnName("aprobado_por");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("calle");

                    b.Property<string>("Categoria")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("categoria");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ciudad");

                    b.Property<decimal>("CostoEnvioBase")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("costo_envio_base");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<long?>("CreadoPor")
                        .HasColumnType("bigint")
                        .HasColumnName("creado_por");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_aprobacion");

                    b.Property<TimeSpan?>("HoraApertura")
                        .HasColumnType("interval")
                        .HasColumnName("hora_apertura");

                    b.Property<TimeSpan?>("HoraCierre")
                        .HasColumnType("interval")
                        .HasColumnName("hora_cierre");

                    b.Property<decimal?>("Latitud")
                        .HasColumnType("numeric(10,8)")
                        .HasColumnName("latitud");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<decimal?>("Longitud")
                        .HasColumnType("numeric(11,8)")
                        .HasColumnName("longitud");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("PortadaUrl")
                        .HasColumnType("text")
                        .HasColumnName("portada_url");

                    b.Property<string>("RedesSociales")
                        .HasColumnType("text")
                        .HasColumnName("redes_sociales");

                    b.Property<string>("Ruc")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ruc");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("AprobadoPor");

                    b.HasIndex("CreadoPor");

                    b.ToTable("restaurantes");
                });

            modelBuilder.Entity("Delivery.Modelos.Entidades.Rol", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("Delivery.Modelos.Entidades.UbicacionActualRepartidor", b =>
                {
                    b.Property<long>("RepartidorId")
                        .HasColumnType("bigint")
                        .HasColumnName("repartidor_id");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<decimal?>("Latitud")
                        .HasColumnType("numeric(10,8)")
                        .HasColumnName("latitud");

                    b.Property<decimal?>("Longitud")
                        .HasColumnType("numeric(11,8)")
                        .HasColumnName("longitud");

                    b.Property<decimal?>("Rumbo")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("rumbo");

                    b.Property<decimal?>("Velocidad")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("velocidad");

                    b.HasKey("RepartidorId");

                    b.ToTable("ubicacion_actual_repartidor");
                });

            modelBuilder.Entity("Delivery.Modelos.Entidades.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellidos");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("FotoPerfilUrl")
                        .HasColumnType("text")
                        .HasColumnName("foto_perfil_url");

                    b.Property<string>("InformacionAdicional")
                        .HasColumnType("text")
                        .HasColumnName("informacion_adicional");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<long?>("RolId")
                        .HasColumnType("bigint")
                        .HasColumnName("rol_id");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.Property<int>("TipoUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_usuario");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("Delivery.Modelos.Entidades.Vehiculo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<short?>("Anio")
                        .HasColumnType("smallint")
                        .HasColumnName("anio");

                    b.Property<string>("Color")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("FotoVehiculoUrl")
                        .HasColumnType("text")
                        .HasColumnName("foto_vehiculo_url");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("marca");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("modelo");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("placa");

                    b.Property<long>("RepartidorId")
                        .HasColumnType("bigint")
                        .HasColumnName("repartidor_id");

                    b.Property<int>("TipoVehiculo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_vehiculo");

                    b.HasKey("Id");

                    b.HasIndex("RepartidorId");

                    b.ToTable("vehiculos");
                });

            modelBuilder.Entity("Delivery.Modelos.Entidades.CategoriaProducto", b =>
                {
                    b.HasOne("Delivery.Modelos.Entidades.Restaurante", "Restaurante")
                        .WithMany("Categorias")
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("Delivery.Modelos.Entidades.Cupon", b =>
                {
                    b.HasOne("Delivery.Modelos.Entidades.Restaurante", "Restaurante")
                        .WithMany()
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("Delivery.Modelos.Entidades.CuponUsuario", b =>
                {
                    b.HasOne("Delivery.Modelos.Entidades.Cupon", "Cupon")
                        .WithMany("CuponesUsuarios")
                        .HasForeignKey("CuponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Delivery.Modelos.Entidades.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("Delivery.Modelos.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cupon");

                    b.Navigation("Pedido");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Delivery.Modelos.Entidades.DetallePedido", b =>
                {
                    b.HasOne("Delivery.Modelos.Entidades.Pedido", "Pedido")
                        .WithMany("Detalles")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Delivery.Modelos.Entidades.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Delivery.Modelos.Entidades.Direccion", b =>
                {
                    b.HasOne("Delivery.Modelos.Entidades.Usuario", "Usuario")
                        .WithMany("Direcciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Delivery.Modelos.Entidades.Favorito", b =>
                {
                    b.HasOne("Delivery.Modelos.Entidades.Restaurante", "Restaurante")
                        .WithMany()
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Delivery.Modelos.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurante");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Delivery.Modelos.Entidades.HistorialAsignacionesRepartidor", b =>
                {
                    b.HasOne("Delivery.Modelos.Entidades.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Delivery.Modelos.Entidades.Repartidor", "Repartidor")
                        .WithMany("HistorialAsignaciones")
                        .HasForeignKey("RepartidorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Repartidor");
                });

            modelBuilder.Entity("Delivery.Modelos.Entidades.Notificacion", b =>
                {
                    b.HasOne("Delivery.Modelos.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Delivery.Modelos.Entidades.Pago", b =>
                {
                    b.HasOne("Delivery.Modelos.Entidades.Pedido", "Pedido")
                        .WithMany("Pagos")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Delivery.Modelos.Entidades.Pedido", b =>
                {
                    b.HasOne("Delivery.Modelos.Entidades.Direccion", "DireccionEntrega")
                        .WithMany()
                        .HasForeignKey("DireccionEntregaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Delivery.Modelos.Entidades.Repartidor", "Repartidor")
                        .WithMany()
                        .HasForeignKey("RepartidorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Delivery.Modelos.Entidades.Restaurante", "Restaurante")
                        .WithMany()
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Delivery.Modelos.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DireccionEntrega");

                    b.Navigation("Repartidor");

                    b.Navigation("Restaurante");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Delivery.Modelos.Entidades.Producto", b =>
                {
                    b.HasOne("Delivery.Modelos.Entidades.CategoriaProducto", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Delivery.Modelos.Entidades.Restaurante", "Restaurante")
                        .WithMany("Productos")
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("Delivery.Modelos.Entidades.RegistroAuditoria", b =>
                {
                    b.HasOne("Delivery.Modelos.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Delivery.Modelos.Entidades.Repartidor", b =>
                {
                    b.HasOne("Delivery.Modelos.Entidades.Usuario", "UsuarioAprobador")
                        .WithMany()
                        .HasForeignKey("AprobadoPor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Delivery.Modelos.Entidades.Usuario", "Usuario")
                        .WithOne()
                        .HasForeignKey("Delivery.Modelos.Entidades.Repartidor", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("UsuarioAprobador");
                });

            modelBuilder.Entity("Delivery.Modelos.Entidades.Resena", b =>
                {
                    b.HasOne("Delivery.Modelos.Entidades.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Delivery.Modelos.Entidades.Repartidor", "Repartidor")
                        .WithMany()
                        .HasForeignKey("RepartidorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Delivery.Modelos.Entidades.Restaurante", "Restaurante")
                        .WithMany()
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Delivery.Modelos.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Repartidor");

                    b.Navigation("Restaurante");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Delivery.Modelos.Entidades.Restaurante", b =>
                {
                    b.HasOne("Delivery.Modelos.Entidades.Usuario", "UsuarioAprobador")
                        .WithMany()
                        .HasForeignKey("AprobadoPor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Delivery.Modelos.Entidades.Usuario", "UsuarioCreador")
                        .WithMany()
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UsuarioAprobador");

                    b.Navigation("UsuarioCreador");
                });

            modelBuilder.Entity("Delivery.Modelos.Entidades.UbicacionActualRepartidor", b =>
                {
                    b.HasOne("Delivery.Modelos.Entidades.Repartidor", "Repartidor")
                        .WithOne("UbicacionActual")
                        .HasForeignKey("Delivery.Modelos.Entidades.UbicacionActualRepartidor", "RepartidorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repartidor");
                });

            modelBuilder.Entity("Delivery.Modelos.Entidades.Usuario", b =>
                {
                    b.HasOne("Delivery.Modelos.Entidades.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Delivery.Modelos.Entidades.Vehiculo", b =>
                {
                    b.HasOne("Delivery.Modelos.Entidades.Repartidor", "Repartidor")
                        .WithMany("Vehiculos")
                        .HasForeignKey("RepartidorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repartidor");
                });

            modelBuilder.Entity("Delivery.Modelos.Entidades.CategoriaProducto", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Delivery.Modelos.Entidades.Cupon", b =>
                {
                    b.Navigation("CuponesUsuarios");
                });

            modelBuilder.Entity("Delivery.Modelos.Entidades.Pedido", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("Delivery.Modelos.Entidades.Repartidor", b =>
                {
                    b.Navigation("HistorialAsignaciones");

                    b.Navigation("UbicacionActual");

                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("Delivery.Modelos.Entidades.Restaurante", b =>
                {
                    b.Navigation("Categorias");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Delivery.Modelos.Entidades.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Delivery.Modelos.Entidades.Usuario", b =>
                {
                    b.Navigation("Direcciones");
                });
#pragma warning restore 612, 618
        }
    }
}
